#### 使用sklearn 的 MLP 实现神经网络

In [51]:
import numpy as np
from sklearn import model_selection # 模型比较和选择包
from sklearn.metrics import confusion_matrix # 计算混淆矩阵，主要用来评估分类准确性
from sklearn.metrics import accuracy_score # 计算精确得分
from sklearn.preprocessing import StandardScaler # 导入标准化库
from sklearn.model_selection import train_test_split # 将数据集划分为训练集和测试集

#### 调用Numpy.genfromtxt函数加载`手写数字`数据集

数据集：https://archive.ics.uci.edu/ml/machine-learning-databases/optdigits/optdigits.tra

#### 使用`sklearn.preprocessing.StandardScaler`对数据特征进行标准化处理
#### 使用`sklearn.model_selection.train_test_split`划分数据集

In [52]:
# 数据集
data_train = np.genfromtxt('optdigits.tra', delimiter=',', dtype=float)
X,y = data_train[:, :-1], data_train[:, -1]
ss = StandardScaler()
ss.fit(X)
X = ss.transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25,random_state=2) 

#### 使用`sklearn.neural_network。MLPClassifier`构建多层感知机实现神经网络训练

In [53]:
from sklearn.neural_network import MLPClassifier # 导入MLP分类器程序库
mlp = MLPClassifier(solver='sgd', activation='logistic' ,alpha=1e-5,hidden_layer_sizes=(50, ), learning_rate_init=0.001, max_iter=2000)
mlp.fit(X_train, y_train)
print("方法：随机梯度下降",mlp.solver)
print ("维数：", mlp.n_layers_)
print ("最终迭代次数：",mlp.n_iter_)
print ("最终损失值：", mlp.loss_)
print ("激活函数：", mlp.out_activation_)                    

方法：随机梯度下降 sgd
维数： 3
最终迭代次数： 946
最终损失值： 0.122810145648955
激活函数： softmax


In [54]:
# 展现训练结果并对测试级进行预测
print("每层网络层系数矩阵维度：\n",[coef.shape for coef in mlp.coefs_])
y_pred = mlp.predict(X_test) # 预测测试集输出
print("预测结果：", y_pred)
print("偏差向量：", mlp.intercepts_) # 列表中第i个元素代表i+1层的偏差向量

每层网络层系数矩阵维度：
 [(64, 50), (50, 10)]
预测结果： [7. 6. 3. 4. 1. 5. 5. 6. 0. 6. 1. 1. 2. 1. 3. 8. 7. 7. 7. 3. 8. 7. 4. 2.
 2. 0. 6. 6. 6. 8. 9. 0. 5. 7. 7. 0. 4. 1. 5. 9. 5. 3. 6. 0. 9. 0. 4. 8.
 7. 0. 5. 1. 9. 0. 9. 3. 6. 2. 8. 1. 7. 0. 2. 6. 2. 5. 0. 0. 7. 6. 9. 1.
 3. 8. 3. 1. 0. 4. 7. 4. 9. 7. 2. 3. 6. 4. 9. 5. 4. 3. 4. 6. 1. 6. 2. 2.
 3. 6. 3. 2. 5. 0. 0. 4. 7. 9. 0. 0. 1. 2. 6. 4. 7. 8. 7. 2. 0. 6. 9. 8.
 3. 8. 9. 6. 2. 6. 6. 9. 3. 4. 2. 8. 3. 9. 5. 7. 7. 3. 3. 6. 0. 6. 9. 0.
 5. 8. 9. 8. 7. 1. 2. 9. 7. 9. 5. 5. 5. 9. 3. 9. 5. 2. 4. 7. 6. 8. 3. 4.
 8. 9. 7. 5. 8. 1. 0. 2. 2. 2. 4. 4. 6. 7. 7. 6. 0. 5. 2. 6. 2. 0. 8. 8.
 1. 3. 0. 3. 3. 5. 8. 1. 3. 4. 0. 6. 4. 5. 2. 6. 6. 1. 7. 2. 5. 2. 0. 0.
 0. 9. 9. 4. 2. 7. 6. 7. 0. 2. 6. 6. 3. 0. 9. 1. 2. 3. 1. 0. 6. 7. 2. 2.
 9. 7. 7. 7. 6. 6. 8. 3. 3. 9. 7. 3. 7. 4. 9. 5. 0. 9. 2. 2. 7. 6. 3. 3.
 0. 8. 8. 8. 1. 8. 0. 9. 1. 1. 2. 6. 1. 3. 5. 6. 5. 5. 3. 9. 6. 9. 6. 1.
 0. 1. 2. 9. 4. 9. 0. 0. 9. 6. 5. 5. 5. 5. 8. 1. 6. 9. 4. 8. 0. 2. 4. 5.
 0. 5. 1. 

In [55]:
print("预测准确率：",accuracy_score(y_test,y_pred))
print("混淆矩阵",confusion_matrix(y_true=y_test,y_pred=y_pred))

预测准确率： 0.9560669456066946
混淆矩阵 [[103   0   0   0   0   0   1   0   0   0]
 [  0 104   0   0   0   0   2   1   2   1]
 [  0   0  99   0   1   0   0   0   3   1]
 [  0   0   2  93   0   1   0   0   1   0]
 [  0   1   0   0  82   0   2   0   2   1]
 [  0   0   0   0   0  96   0   0   0   1]
 [  0   1   0   0   0   0  95   0   1   0]
 [  0   0   0   0   0   0   0  86   0   0]
 [  1   3   0   0   1   2   0   0  78   0]
 [  0   2   0   2   1   0   0   4   1  78]]
